# Generated by Django 5.2.16 on 2026-07-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplyExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incoming_message",
                    models.TextField(
                        help_text="Example message received from a contact."
                    ),
                ),
                (
                    "bilal_reply",
                    models.TextField(
                        help_text="Bilal-style reply to use as tone, wording, and Roman Urdu guidance."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
